/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import MachineLearning.Network;
import java.util.Arrays;

/**
 *
 * @author Annamari
 */
public class MainFrame extends javax.swing.JFrame {

        private final int WIDTH = 500;
        private final int HEIGHT = 800;

    public MainFrame() {
        initComponents();
        setting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel1 = new GUI.RegistrationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gépelési dinamika");

        panel1.setBackground(new java.awt.Color(133, 150, 166));
        panel1.setForeground(new java.awt.Color(168, 182, 191));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().start();
            }
        });
    }

    private void setting() {
        this.setSize(WIDTH, HEIGHT);
        this.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.RegistrationPanel panel1;
    // End of variables declaration//GEN-END:variables
    
    private void start() {
        System.out.print(System.getProperty("java.home"));
        setVisible(true);
        setResizable(false);
        Controller controller = new Controller(panel1, this);
        panel1.setController(controller);
        panel1.setFocusable(true);
        controller.setting();
        
       Network net = new Network(4,3,3,2);
       double[] input = new double[]{0.1,0.2,0.3,0.4};
       double[] target = new double[]{1,0};
       
       double[] input2 = new double[]{0.6,0.1,0.4,0.8};
       double[] target2 = new double[]{0,1};
       
        for (int i = 0; i < 10000; i++) {
            net.train(input, target, 0.3);
            net.train(input2, target2, 0.3);
        }
        System.out.println();
        System.out.println("--------------- TEST ----------------");
       System.out.println(Arrays.toString(net.calculate(input)));
       System.out.println(Arrays.toString(net.calculate(input2)));
       System.out.println("--------------- END TEST ----------------");
       
    }
}
