/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Controller.Controller;
import java.awt.BorderLayout;
import javax.swing.WindowConstants;

/**
 *
 * @author Annamari
 */
public class LoginFrame extends javax.swing.JFrame {

        private final int WIDTH = 350;
        private final int HEIGHT = 300;
        private Controller controller;
    
    public LoginFrame(Controller controller) {
        initComponents();
        this.controller = controller;
        settings();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        reigstrationPanel2 = new GUI.LoginPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejelentkezés");

        reigstrationPanel2.setBackground(new java.awt.Color(166, 171, 129));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reigstrationPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reigstrationPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settings() {
        this.setSize(WIDTH, HEIGHT);
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
        this.setVisible(true);
        setResizable(false);
        reigstrationPanel2.setController(controller);
        reigstrationPanel2.setFocusable(true);
        controller.setLoginPanel(reigstrationPanel2);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.LoginPanel reigstrationPanel2;
    // End of variables declaration//GEN-END:variables

    
}
